- extractor: biliuserupload
  filter: no-song-cut
  last_url: https://www.bilibili.com/video/BV1D6JEziEtS
  url: https://space.bilibili.com/1535934003/upload/video
- extractor: biliseries.new
  filter: no-song-cut
  last_url: https://www.bilibili.com/video/BV1McJEzPEv7
  url: https://space.bilibili.com/1351761831/lists/495256?type=series
