version: "3.9"
services:
  inaseg:
    image: ipynb-inaseg
    build: .
    volumes:
      - .:/inaseg
    user: "0:0"
    command: python /inaseg/watcher.py --watch_interval=43200
    restart: unless-stopped
  inacelery:
    image: ipynb-inaseg
    build: .
    volumes:
      - .:/inaseg
    user: "0:0"
    command: celery -A inacelery worker -c 1 --loglevel=info
    restart: unless-stopped
